
default: all

CFLAGS=	-O -Wall -Werror

all: assemble-sections extract-sections

assemble-sections: assemble-sections.o

extract-sections: extract-sections.o

clean:
	rm -f assemble_sections
	rm -f extract_sections
	rm -f *.o
